
// Auto Generated File
// Do not edit this file, edit MsgId.tt
namespace GameCommon.Contracts.Message {
    public static class MSGID {
        public const uint CompAdded = 0;
        public const uint CompRemoved = 1;
        public const uint EnteringMap = 2;
        public const uint EnteredMap = 3;
        public const uint LeftingMap = 4;
        public const uint LeftedMap = 5;
        public const uint Collided = 6;
        public const uint MSG_FO_Created = 7;
        public const uint MSG_FO_Initialized = 8;
    }
}


